/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Fixed.hpp                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: alsiavos <alsiavos@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/11/15 13:46:55 by alsiavos          #+#    #+#             */
/*   Updated: 2024/11/18 16:36:15 by alsiavos         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef FIXED_HPP
# define FIXED_HPP

#include "Color.hpp"
#include <iostream>
#include <string>
#include <cmath>
#include <fstream>

class Fixed {
	private:
		int _value;
		static const int _bits = 8;
	public:
		Fixed(); // connonical default
		Fixed(const Fixed &src); // connonical copy
		Fixed(int const &value); // constructor with int
		Fixed(float const &value); // constructor with float
		~Fixed(); // connonical destructor
		Fixed &operator=(const Fixed &rhs); // connonical operator= overload
		int getRawBits(void) const; // getter for _value
		void setRawBits(int const raw); // setter for _value
		float toFloat(void) const; // convert to float
		int toInt(void) const; // convert to int
};

std::ostream &operator<<(std::ostream &o, Fixed const &rhs); // operator<< overload for Fixed

#endif
// cannonical = means the default functions that are generated by the compiler if they are not defined by the programmer
